.github/workflows/main.yml

yaml
name: Match Checker (Hourly)

on:
schedule:
- cron: '0 * * * *' # Runs every hour
workflow_dispatch: # Allows manual run from GitHub

jobs:
run:
runs-on: ubuntu-latest
steps:
- name: Checkout code
  uses: actions/checkout@v3

- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'

- name: Install dependencies
  run: pip install -r requirements.txt

- name: Run match checker
  run: python match_checker.py
